name: Run pandoc

on: [push]

jobs:
  pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"
      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '2.18' # The pandoc version to download (if necessary) and use.
      - run: sudo apt install context
      - run: pandoc --version
      - run: make all
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*.pdf"
          body: "Resume compiled"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.date.outputs.date }}
