name: Run pandoc

on: [push]

jobs:
  pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix build
      - run: copy result/resume.pdf .
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*.pdf"
          body: "Resume compiled"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.date.outputs.date }}
